### ISSUE TITLE
Wheel package for 3.1.1 not available on PyPI

### ISSUE THREAD

**Issue by atodorov** [jazzband/django-simple-history#987] opened 2022-05-11 18:20 UTC
**Describe the bug**
For 3.1.1 only a tar.gz source package is available on PyPI while previous releases included wheel packages. 

Can we get the py3 wheel package uploaded to PyPI ?

**Comment by tmc9031** [comment] 2022-05-20 16:03
me too tar.gz

```
> pip install -U django-simple-history
Requirement already satisfied: django-simple-history in c:\program\python3v\lib\site-packages (3.0.0)
Collecting django-simple-history
  Downloading django-simple-history-3.1.1.tar.gz (544 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... error
  ERROR: Command errored out with exit status 1:
```

**Comment by jeking3** [comment] 2022-06-07 11:56
This will require a 3.1.2 release.  The root cause can be traced to the release workflow in GitHub Actions:
https://github.com/jazzband/django-simple-history/commit/60beaf4d5157c2512da320e2ee436769a2fa061a#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R31

That should be doing a "make dist" instead of what it is doing:
https://github.com/jazzband/django-simple-history/blob/master/Makefile#L29-L34

However the gpg signing may not work in GitHub Actions - not sure.

**Comment by ddabble** [comment] 2023-09-15 19:22
Closing, as [3.1.1 is (now) on PyPI](https://pypi.org/project/django-simple-history/3.1.1/).

**Closed by ddabble** 2023-09-15 19:22 UTC
