### ISSUE TITLE
ValidationError exception on UUID

### ISSUE THREAD

**Issue by bedros** [jazzband/django-simple-history#299] opened 2017-07-05 01:17 UTC
my model is as follows

id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False) 
name = models.CharField(max_length=255)
    description = models.CharField(max_length=2047, blank=True, null=True)
    case_number = models.CharField(max_length=255, blank=True, null=True)
    about_person  = models.ManyToManyField('Person', blank=True, related_name="about_person_case")
history = HistoricalRecords()

when I click on history in admin I get error page with following

["Content of description field' is not a valid UUID."]

why it takes content of description as the UUID?

my __str__ is not simple,

`def __str__(self):
     return str(self.name + " about " + self.about_person)`

if I change __str__ to 
`def __str__(self):
    return str(self.name)`

problem goes away, but I need __str__ to return name and about person

**Comment by bedros** [comment] 2017-07-05 01:37
actually, after changing str to return name, in simple history admin page, under object column, I get "None" not the value of name

**Comment by bedros** [comment] 2017-07-05 03:34
after adding print(self.pk) and print(self.id) inside __str__ function, I get the content value of the field description printed for self.pk and self.id

**Comment by bedros** [comment] 2017-07-05 03:57
I did not mention that I have modified_on and modified_by fields for simplicity, and I added those fields to excluded_fields

however, once I removed the excluded_fields from HistoricalRecords I got it to work fine with no problems.

**Comment by macro1** [comment] 2017-07-05 07:01
I'm not sure I can speak directly to the issues you're seeing, but I would suggest you limit your string representations to fields on the model itself, to avoid extra DB queries.

Since `about_person` is a `ManyToManyField` `def __str__(self): return str(self.name + " about " + self.about_person)` will attempt to generate a string representation of the set of related models, which may require a database query.

String representations should be limited to fields on the table associated with the model that we can expect will be already present in memory at the time `__str__()` is called.

So two comments here I guess, but they're really not related to simple_history, as the way you're customizing `__str__()` makes me think there's more going on.

If the requirement is that the admin display information about both the model with `name` (Case?) and information in the related `about_person` fields (On Person.), I suggest configuring the admin to make that more detailed description, rather than assuming that all parts of your application will be willing to make those additional database calls.

My second comment is on whether you actually want `about_person` to be a `ManyToManyField`. It sounds like you might just want a normal `ForeignKey`. Can a specific case be related to more than one person?

**Comment by bedros** [comment] 2017-07-05 18:33
Marco, thanks for raising valid points.

a user may create a case called "Documents about John Smith" however, since the user already entered in the case, about a person "John Smith" the case name has redundancy. it would be better to name the case "Documents" and then the display name of case is "Documents about John Smith"

for the second part, I tried to make it as much flexible as possible, however, there are rare cases where we need M2M in about fields, and most importantly, it would be hard to switch from M2M to FK (for performance reasons) if users already used multiple entries in the m2m field. we can always switch from FK to M2M in future if we need it.

for using multiple DB queries in `__str__` I find it a better user experience not having to enter "about some person" in the name of the case, since the case already has that info, and we can fix DB performance from this with read only DB slaves.

**Comment by rossmechanic** [comment] 2018-04-09 00:37
@bedros did you ever find a fix for this?

**Comment by jeking3** [comment] 2021-09-16 20:08
ManyToManyField is not supported; there are numerous issues about it here.

**Comment by ddabble** [comment] 2023-10-22 23:48
Assuming that the issue is resolved now that support for M2M fields has been added. Please reopen if it's still not resolved.

**Closed by ddabble** 2023-10-22 23:48 UTC
