### ISSUE TITLE
IntegrityError when deleting user

### ISSUE THREAD

**Issue by BojanKogoj** [jazzband/django-simple-history#391] opened 2018-05-15 15:25 UTC
I get the following exception when I try to delete a user.
```
IntegrityError at /admin/...

update or delete on table "abc_auth_user" violates foreign key constraint "measurements_histo_history_user_id_d76dbbe3_fk_abc_auth_user_id" on table "measurements_historicalusermeasurements"
DETAIL:  Key (id)=(36) is still referenced from table "measurements_historicalusermeasurements".
```

As far as I can see it should set [history_user to NULL](https://github.com/treyhunner/django-simple-history/blob/d3d8a25059690d56c2cc683e6acd19e34439ad9a/simple_history/models.py#L237) (if that's even the problem).

I'm getting this in a working code and not tests. Any known solution? It's making deleting users near impossible. I'm using version 1.9.1

**Comment by rossmechanic** [comment] 2018-05-15 16:00
Can you show me your model definition for `UserMeasurements`? There shouldn't be any db_constraints on the historical table's foreign keys because of this line: https://github.com/treyhunner/django-simple-history/blob/master/simple_history/models.py#L163

Seeing that table might help me try to help you debug.

**Comment by BojanKogoj** [comment] 2018-05-16 06:32
I removed a bunch of fields but that's it. No explicit constraints.

```python
class UserMeasurements(models.Model):

    weight = models.DecimalField(
        _('weight'), default=None, null=True, blank=True,
        max_digits=10, decimal_places=2)

    # .....

    created = models.DateTimeField(
        _('created'), auto_now_add=True)

    updated = models.DateTimeField(
        _('updated'), auto_now=True)

    history = HistoricalRecords()

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, related_name='measurements_user')

models.signals.post_save.connect(
    measurements_updated, sender=UserMeasurements, dispatch_uid='measurements_updated')
```

**Comment by kacperd** [comment] 2018-05-20 14:10
I have the same issue when deleting user. I have following model:

`class Phone(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    history = HistoricalRecords()

    os = models.CharField(max_length=255, blank=True, null=True)
    os_version = models.CharField(max_length=255, blank=True, null=True)
    app_version = models.CharField(max_length=255, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
`

And I'm getting: 
`IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`test_invis`.`phone_historicalphone`, CONSTRAINT `phone_historicalphone_history_user_id_9d6458c1_fk_auth_user_id` FOREIGN KEY (`history_user_id`) REFERENCES `auth_user` (`id`))')
`
I tested that this happens on MySQL database. On SQLLite this problem is not appearing.

**Comment by rossmechanic** [comment] 2018-05-29 22:40
Thanks for digging into this issue @kacperd . Going to add different dbs to the testing suite so that we catch this earlier on and can figure out what's going on with simple-history. DB constraints should be off, so it may be a MySQL issue. Tried recreating locally with postgres but couldn't find any issues. Hopefully when I setup the tests to test on MySQL I can pinpoint the bug.

**Comment by rwlogel** [comment] 2018-09-28 19:14
I have run into this same issue with Postgres.

**Comment by rwlogel** [comment] 2018-09-28 19:41
I was able to reproduce a similar problem by updating the `test_specify_history_user` in `test_models.py` to the following:
```
    def test_specify_history_user(self):
        user1 = User.objects.create_user('user1', '1@example.com')
        user2 = User.objects.create_user('user2', '1@example.com')
        document = Document.objects.create(changed_by=user1)
        document.changed_by = user2
        document.save()
        document.changed_by = None
        document.save()
        self.assertEqual([d.history_user for d in document.history.all()],
                         [None, user2, user1])

        # Change back to user1
        document.changed_by = user1
        document.save()
   
        # Deleting user1 will cascade delete the document, but fails when it tries to make the historical
        # record for the deleted user1.
        user1.delete()
```

**Comment by rossmechanic** [comment] 2018-09-28 20:17
Thanks for this @rwlogel. Same error that shows up?

**Comment by keithhackbarth** [comment] 2020-06-24 18:32
This should be fixed by applying the `user_db_constraint` constraint in version 2.11.0. I believe this issue can be closed as a result.

**Closed** 2020-06-25 18:32 UTC
Labels: bug

**Comment by solace** [comment] 2020-12-02 13:10
Hi @keithhackbarth and/or @rossmechanic,

I was encountering this problem with a model that has an author user model foreign key (similar to a blog post with author reference). Deleting the author raises the IntegrityError.

I saw https://github.com/jazzband/django-simple-history/issues/697#issuecomment-729951676 from a couple weeks ago where it is recommended to manually track the user model. I attempted this, but ended up with an IntegrityError against the history user id instead.

Undoing the manual tracking changes and setting user_db_constraint to false seems to resolve the issue.

Which method is preferred for preventing IntegrityErrors on user deletion?

Thanks!
