### ISSUE TITLE
Allow db_index=False for historical fields

### ISSUE THREAD

**Issue by humphrey** [jazzband/django-simple-history#909] opened 2021-11-10 04:54 UTC
**Problem Statement**
I have an 1500MB DB index on my historical table, which have been created for fields which do not need to indexed in a historical context.  Having db_index=True on the primary model works great, but since there are lots of historical versions (db table has over 9,000,000 rows), I do not want to index a couple of the fields.

**Describe the solution you'd like**
Either:
1. Allow me to specify a list of fields to set `db_index=False` for.
2. Set db_index=False by default for all fields that are not Foreign Keys.  

**Describe alternatives you've considered**
- Adding those fields to "excluded_fields".
- Writing an manual migration to drop the indices.  But this may cause migration issues down the track.

**Additional context**
For large tables, it can make sense to have db_index=True on fields you would like to search or sort by.  However, there is not a need to search for the historical versions of those (in my use cases) since I access the historical models via the current model.

Thanks!!  I've already trawled through the source code looking for a workaround... so I'd be happy to put together a pull request if that would be helpful.

**Comment by jeking3** [comment] 2021-11-13 02:53
There is an open PR for item 1 in your list: #782 however the author hasn't been able to complete it.  Perhaps you could assist?

There is also code in the master branch that has not been released, as seen in #863, to control indexing on the history_date field.

**Comment by jeking3** [comment] 2021-11-13 02:54
This is a duplicate of #720.

**Comment by Sult** [comment] 2021-12-08 11:52
Updated the PR. Should be ready to use again.

**Comment by humphrey** [comment] 2021-12-09 04:52
Thanks!

However, I think the easier way for me to solve this (for my current issue) will be to just custom code a History Table, as a simple log will suit this use case better than the full django-simple-history approach.

**Closed** 2022-01-18 11:51 UTC
