### ISSUE TITLE
Grabbing Subsequent Fields Change Old and New Values   

### ISSUE THREAD

**Issue by inayet** [jazzband/django-simple-history#839] opened 2021-06-09 19:33 UTC
**Problem Statement**
I can get all the fields that were changed, however only the first new and old value of the first field that was changed appears, my code does not grab the next field's old and new value that were changed.  I have attached an image that illustrates this. Is this a limitation of django-simple-history module or my code below ? 

**Describe the solution you'd like**
I would like to be able to grab all of the changes that happened in each field, and output to the admin area.

**Describe alternatives you've considered**
I have tried using for loops and if statements but I do not get the solution that I would like. 

**Additional context**

`
    history_list_display = ['changed_fields', 'changed_values']

    def changed_values(self,obj):
        if obj.prev_record:
            delta = obj.diff_against(obj.prev_record)
            for change in delta.changes:
                return f'Changed Field: "{change.field}" | Old value: "{change.old}" | New value: "{change.new}"'

    def changed_fields(self, obj):

        if obj.prev_record:
            delta = obj.diff_against(obj.prev_record)
            return f'The field(s) that were changed: "{delta.changed_fields}"'

            # for change in delta.changes:
            #     return f'The field that was changed: "{change.field}". The old value: "{change.old}". The new value "{change.new}"'
        return None
`

![a](https://user-images.githubusercontent.com/8376206/121415806-56abba80-c925-11eb-9546-c54c795a7ec4.JPG)

**Comment by inayet** [comment] 2021-06-09 22:07
I wanted to say how useful django-simple-history module is, thank you all for working on it, and hopefully one day I can be at a level to contribute.

**Comment by inayet** [comment] 2021-06-09 22:28
I think the problem is with my code. Once I find a solution I will paste it here in the comments.

**Comment by inayet** [comment] 2021-06-10 03:43
Good thing, it was my code that was faulty. Here is the working version for anyone in the future who might encounter the same issue I did. 

`     
history_list_display = ['changed_fields', 'changed_values']

    def changed_values(self,obj):
        messagelist = ""
        if obj.prev_record:
            delta = obj.diff_against(obj.prev_record)
            for change in delta.changes:
                messagelist += (f' | Field: {change.field} - Old Value: {change.old} - New Value: {change.new}')
           

        return messagelist`

This returns all the fields that were changed and their old and new values.

**Comment by jeking3** [comment] 2021-09-17 01:24
Great to head; close this issue out if your issue was resolved, otherwise let us know what's left.  Thanks.

**Comment by ddabble** [comment] 2023-09-28 18:51
Closing, now that the issue is resolved.

**Closed by ddabble** 2023-09-28 18:51 UTC
