### ISSUE TITLE
Tracking model history with foreign key points to the latest object only

### ISSUE THREAD

**Issue by rashedoz** [jazzband/django-simple-history#711] opened 2020-09-18 06:38 UTC
When tracking history with a foreign key field. History always points to the latest foreign key value. How can I point to the value at that point of time?

For Example: 

I have three models with historical records:

```
class WifiUser(models.Model):
    ....
    wifiDevice = models.OneToOneField(WifiDevice, on_delete=models.CASCADE, default=None)
    wifiSim = models.OneToOneField(WifiSim, on_delete=models.CASCADE, default=None)
    history = HistoricalRecords()

class WifiDevice(models.Model):
    ....
    history = HistoricalRecords()

class WifiSim(models.Model):
    ....
    history = HistoricalRecords()
```

I want to keep track of history with corresponding foreign key history records. But when accessing the history of Wifiuser I get the latest values of WifiDevice and WifiSim. I want the historical record of WifiDevice and WifiSim to point to that record of their one. Whats the best method to follow for this?

For reference stack question -> [stackoverflow](https://stackoverflow.com/questions/62478916/django-model-history-with-foreign-keys-history-tracking-using-django-simple-hist)

**Comment by rossmechanic** [comment] 2020-11-18 20:56
We don't currently support m2m relations on history. This is a duplicate of #399

**Closed by rossmechanic** 2020-11-18 20:56 UTC
