### ISSUE TITLE
MySQL Exceptions taking preference during testing

### ISSUE THREAD

**Issue by surfer190** [jazzband/django-simple-history#325] opened 2017-11-15 08:32 UTC
When testing you will find many tests ailing with an error like the below:

```
_mysql_exceptions.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`test_my_project`.`users_historicaluser`, CONSTRAINT `users_historicaluser_history_user_id_7f91d047_fk_users_user_id` FOREIGN KEY (`history_user_id`) REFERENCES `users_user` (`id`))')
```

After removing the history references you can uncover the real error:

```
"the 'fields' attribute is prohibited." % self.__class__.__name__
django.core.exceptions.ImproperlyConfigured: Using ModelFormMixin (base class of EntryUpdateView) without the 'fields' attribute is prohibited.
```

It is a shame that the library is hiding errors during testing, so had to remove the package.
Would be nice if it could be turned off during testing,.

**Comment by macro1** [comment] 2017-11-30 16:54
When you generate a test user, do you save it to the database? Or do you generate mock 'users' that are not present in the database throughout your tests to save on database calls? The foreign key constraint is indicating that a history record was saved with a `user_id` that is not present in your `users_user` table.

It looks to me like django-simple-history is accidentally surfacing a situation where the environment set up for that test does not match something you would find in production.

Maybe temporarily you could remove the middleware that allows for user tracking, and see if that removes the errors. If it does, you may need to save the users you're using to make test requests to the database before tests with django-simple-history will work.

**Comment by surfer190** [comment] 2017-12-04 09:26
I am saving to the database:

```
def setUp(self):
        self.user = get_user_model().objects.create_user(
            email='mytest@user.com',
            password='1234pass',
            company_id=1
        )
```

Yes, it looks like the situation is accidently surfacing. An interesting thing though is the error only pops up when the a test fails. If all is fine, then all tests pass without issue.
It is making fixing tests quite hard, so had to remove the package.

**Comment by jeking3** [comment] 2021-09-17 22:07
This does not look like an issue that needs to remain open as the user abandoned use of the project.  The root cause was not ascertained and no further action had been taken.  Closing.

**Closed by jeking3** 2021-09-17 22:07 UTC
