### ISSUE TITLE
skip_history_when_saving if model has no any changes

### ISSUE THREAD

**Issue by KevinFan1** [jazzband/django-simple-history#1330] opened 2024-05-13 06:11 UTC
Hi!
Is there any ways that i can skip history when model is saving without any changes?  I don't want to save multiple same records in database

**Comment by ddabble** [comment] 2024-05-15 01:41
One way would be to [set `skip_history_when_saving = True`](https://django-simple-history.readthedocs.io/en/3.5.0/querying_history.html#save-without-a-historical-record) on each model instance if you know that no changes have been made (or just avoid calling `save()` altogether) 🙂 ..but I'm assuming that you meant that you would prefer that `django-simple-history` automatically detects that no changes have been made, and then skips creating a historical record; is this the case?

**Comment by ddabble** [comment] 2024-06-06 17:02
Assuming the latter (described in my comment above), so closing as duplicate of #302. Please reopen if that's not the case 🙂

**Comment by ddabble** [comment] 2024-06-06 17:03
Duplicate of #302

**Closed by ddabble** 2024-06-06 17:03 UTC
