### ISSUE TITLE
Custom m2m field are not handled correctrly

### ISSUE THREAD

**Issue by PiotrKurnik** [jazzband/django-simple-history#1094] opened 2023-01-03 10:31 UTC
**Describe the bug**

**To Reproduce**
Code snippet below illustrates the issue. There are assumptions to the name of the fields in through tables for m2m tables.
For the default through tables it works, but for the custom ones it does not.

If you try to save object of PageArticle you will see:
```
django.core.exceptions.FieldError: Cannot resolve keyword 'pagearticle' into field. Choices are: article, article_id, id, tag, tag_id
```
```
from django.db import models
from simple_history.models import HistoricalRecords

class Tag(models.Model):
    name = models.CharField(max_length=100)

class ArticleTag(models.Model):
    article = models.ForeignKey("PageArticle", on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)

class PageArticle(models.Model):
    title = models.CharField(max_length=100)
    article_tags = models.ManyToManyField(Tag, through=ArticleTag)

    history = HistoricalRecords(m2m_fields=[
        article_tags,
    ])
```
**Expected behavior**
A model should be saved without any errors.

**Screenshots**
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/3011152/210339903-7199a18e-96b1-4d4e-a561-4d49636505e3.png">

**Environment (please complete the following information):**
 - OS: MacOS, Windows
 - Browser (if applicable): [e.g. chrome, safari]
 - Django Simple History Version: 3.2.0
 - Django Version: 4.1.5

**Additional context**
Pull request that addresses the issue is #1093

**Comment by uy-rrodriguez** [comment] 2023-09-05 19:12
Is this a duplicate of #1093 ?

**Comment by ddabble** [comment] 2023-09-26 14:55
See https://github.com/jazzband/django-simple-history/pull/1093#issuecomment-1735713366.

**Closed by ddabble** 2023-09-26 14:55 UTC
