### ISSUE TITLE
Add support for HistoricOneToOneField

### ISSUE THREAD

**Issue by JordanHyatt** [jazzband/django-simple-history#1389] opened 2024-09-11 21:47 UTC
HistoricForeignKey is a very nice feature, it would be great to extend this support to OneToOneFields.

**Comment by kgeidel** [comment] 2024-09-11 23:18
Yes, that would be swell. HistoricForeignKey(unique=True) throws that warning about using one to one. Would be nice to be able to have history on the 1-1 w/o needing to suppress that warning.

**Comment by ddabble** [comment] 2024-11-24 18:37
Duplicate of #1031

**Closed** 2024-11-24 18:37 UTC
